name: etc-websockets
version: '0.0.1.0'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/mvc-socket
extra-source-files:
- stack.yaml
- readme.md
library:
  source-dirs: src
  ghc-options:
    - -funbox-strict-fields
  dependencies:
    - aeson
    - async
    - base
    - data-default
    - etc
    - flow
    - generic-lens-labels
    - lens
    - managed
    - network
    - pipes-concurrency
    - protolude
    - streaming
    - text
    - websockets
  exposed-modules:
    - Etc.WebSockets

executables:
  wsdebug:
    main: wsdebug.hs
    source-dirs: app
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - etc-websockets
    - aeson
    - async
    - base
    - bytestring
    - contravariant
    - data-default
    - flow
    - generic-lens-labels
    - etc
    - lens
    - managed
    - network
    - optparse-generic
    - pipes
    - pipes-concurrency
    - profunctors
    - protolude
    - streaming
    - text
    - websockets
