name: websocket-box
version: '0.0.1.0'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/websocket-box
extra-source-files:
  - stack.yaml
  - readme.md
library:
  source-dirs: src
  ghc-options:
    - -funbox-strict-fields
  dependencies:
    - aeson
    - async
    - base
    - data-default
    - box
    - flow
    - generic-lens-labels
    - lens
    - managed
    - network
    - pipes-concurrency
    - protolude
    - streaming
    - text
    - websockets
  exposed-modules:
    - Box.WebSockets

executables:
  esocket:
    main: app.hs
    source-dirs: app
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - websocket-box
    - aeson
    - async
    - base
    - bytestring
    - contravariant
    - data-default
    - flow
    - generic-lens-labels
    - box
    - lens
    - managed
    - network
    - optparse-generic
    - pipes
    - pipes-concurrency
    - profunctors
    - protolude
    - streaming
    - text
    - time
    - websockets
