name: mvc-socket
version: '0.0.1'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/mvc-socket
extra-source-files:
- other/lhs.css
- other/header.md
- other/footer.md
default-extensions:
- BangPatterns
- BinaryLiterals
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DisambiguateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NegativeLiterals
- NoImplicitPrelude
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- TupleSections
- TypeFamilies
- TypeOperators
- UnicodeSyntax
dependencies:
- base >=4.7 && <5
- mvc-extended
library:
  source-dirs: src
  ghc-options:
    - -funbox-strict-fields
  dependencies:
    - aeson
    - async
    - data-default
    - generic-lens-labels
    - lens
    - managed
    - mvc
    - mvc-extended
    - network
    - pipes
    - protolude
    - text
    - websockets
    - iso
    - flow
    - streaming
    - streaming-concurrency
  exposed-modules:
    - MVC.Socket

executables:
  wsdebug:
    main: wsdebug.hs
    source-dirs: app
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - async
    - data-default
    - generic-lens-labels
    - lens
    - managed
    - mvc
    - mvc-extended
    - mvc-socket
    - network
    - pipes
    - protolude
    - text
    - websockets
    - protolude
    - optparse-generic
    - iso
    - websockets
    - iso
    - flow
    - streaming
    - streaming-concurrency
    - pipes-concurrency
    - contravariant
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - HUnit
    - QuickCheck
    - doctest
    - protolude
    - tasty
    - tasty-hunit
    - tasty-quickcheck
